SINAN.Presentation.Web/Controllers/RelatoriosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcRazorToPdf;
using AutoMapper;
using SINAN.Domain.Entities;
using SINAN.Domain.Interfaces.Repository;
using SINAN.Application.Interfaces;
using SINAN.Application.ViewModel;
using SINAN.Infrastructure.CrossCutting.Helpers;

namespace SINAN.Controllers
{
    [Authorize]
    public class RelatoriosController : Controller
    {
        private readonly IUnitOfWork _uow;

        public RelatoriosController(IUnitOfWork uow)               
        {
            _uow = uow;
        }

        // GET: Relatorios/Sinan
        public PdfActionResult Sinan(int? Id)
        {
            var sinan = _uow.GetRepository<Sinan>().GetById(Id);
            var sinanDadosGerais = _uow.GetRepository<Sinan_DadosGerais>().GetById(Id);
            var sinanNotificacaoIndividual = _uow.GetRepository<Sinan_NotificacaoIndividual>().GetById(Id);
            var sinanDadosResidencia = _uow.GetRepository<Sinan_DadosResidencia>().GetById(Id);
            var sinanDadosDePessoaAtendida = _uow.GetRepository<Sinan_DadosDePessoaAtendida>().GetById(Id);
            var sinanDadosDaOcorrencia = _uow.GetRepository<Sinan_DadosDaOcorrencia>().GetById(Id);
            var sinanViolencia = _uow.GetRepository<Sinan_Violencia>().GetById(Id);
            var sinanViolenciaSexual = _uow.GetRepository<Sinan_ViolenciaSexual>().GetById(Id);
            var sinanDadosDoProvavelAutorDaViolencia = _uow.GetRepository<Sinan_DadosDoProvavelAutorDaViolencia>().GetById(Id);
            var sinanEncaminhamento = _uow.GetRepository<Sinan_Encaminhamento>().GetById(Id);
            var sinanDadosFinais = _uow.GetRepository<Sinan_DadosFinais>().GetById(Id);
            var sinanObservacoes = _uow.GetRepository<Sinan_Observacoes>().GetById(Id);
            var sinanNotificador = _uow.GetRepository<Sinan_Notificador>().GetById(Id);

            var viewmodel = new SinanViewModel
            {
                Id = sinan.id,
                usu_codigo = sinan.usu_codigo,
                data_envio = sinan.data_envio,
                Sinan_DadosGeraisViewModel = Mapper.Map<Sinan_DadosGerais, Sinan_DadosGeraisViewModel>(sinanDadosGerais),
                Sinan_NotificacaoIndividualViewModel = Mapper.Map<Sinan_NotificacaoIndividual, Sinan_NotificacaoIndividualViewModel>(sinanNotificacaoIndividual),
                Sinan_DadosResidenciaViewModel = Mapper.Map<Sinan_DadosResidencia, Sinan_DadosResidenciaViewModel>(sinanDadosResidencia),
                Sinan_DadosDePessoaAtendidaViewModel = Mapper.Map<Sinan_DadosDePessoaAtendida, Sinan_DadosDePessoaAtendidaViewModel>(sinanDadosDePessoaAtendida),
                Sinan_DadosDaOcorrenciaViewModel = Mapper.Map<Sinan_DadosDaOcorrencia, Sinan_DadosDaOcorrenciaViewModel>(sinanDadosDaOcorrencia),
                Sinan_ViolenciaViewModel = Mapper.Map<Sinan_Violencia, Sinan_ViolenciaViewModel>(sinanViolencia),
                Sinan_ViolenciaSexualViewModel = Mapper.Map<Sinan_ViolenciaSexual, Sinan_ViolenciaSexualViewModel>(sinanViolenciaSexual),
                Sinan_DadosDoProvavelAutorViolenciaViewModel = Mapper.Map<Sinan_DadosDoProvavelAutorDaViolencia, Sinan_DadosDoProvavelAutorViolenciaViewModel>(sinanDadosDoProvavelAutorDaViolencia),
                Sinan_EncaminhamentoViewModel = Mapper.Map<Sinan_Encaminhamento, Sinan_EncaminhamentoViewModel>(sinanEncaminhamento),
                Sinan_DadosFinaisViewModel = Mapper.Map<Sinan_DadosFinais, Sinan_DadosFinaisViewModel>(sinanDadosFinais),
                Sinan_ObservacoesViewModel = Mapper.Map<Sinan_Observacoes, Sinan_ObservacoesViewModel>(sinanObservacoes),
                Sinan_NotificadorViewModel = Mapper.Map<Sinan_Notificador, Sinan_NotificadorViewModel>(sinanNotificador)
            };            

            return new PdfActionResult("Sinan", viewmodel);
        }        
    }
}

SINAN.Presentation.Web/Controllers/SinanController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using PagedList.Mvc;
using AutoMapper;
using PagedList;
using SINAN.Domain.Entities;
using SINAN.Domain.Interfaces.Repository;
using SINAN.Application.Interfaces;
using SINAN.Application.ViewModel;
using SINAN.Infrastructure.CrossCutting.Helpers;

namespace SINAN.Controllers
{
    [Authorize]
    public class SinanController : Controller
    {
        private readonly IUnitOfWork _uow;        
        private readonly IBairroAppService _bairroApp;
        private readonly ILogradouroAppService _logradouroApp;
        private readonly IMunicipioAppService _municipioApp;
        private readonly IUnidadeAppService _unidadeApp;

        public SinanController(IUnitOfWork uow,            
            IBairroAppService bairroApp,
            ILogradouroAppService logradouroApp,
            IMunicipioAppService municipioApp,
            IUnidadeAppService unidadeApp)
        {
            _uow = uow;            
            _bairroApp = bairroApp;
            _logradouroApp = logradouroApp;
            _municipioApp = municipioApp;
            _unidadeApp = unidadeApp;
        }
        
        // GET: Sinan/Listar
        public ActionResult Listar(string searchNome,
            DateTime? searchDataNascimento,
            string searchCartaoSUS,
            int? searchMotivoOcorrencia,
            DateTime? searchDataOcorrencia,
            int? page)
        {
            var obj = (from sinan in _uow.GetRepository<Sinan>().Get()
                       join sinanNoticacaoIndividual in _uow.GetRepository<Sinan_NotificacaoIndividual>().Get() on sinan.id equals sinanNoticacaoIndividual.id
                       join sinanDadosGerais in _uow.GetRepository<Sinan_DadosGerais>().Get() on sinan.id equals sinanDadosGerais.id
                       join sinanViolencia in _uow.GetRepository<Sinan_Violencia>().Get() on sinan.id equals sinanViolencia.id
                       select new
                       {
                           searchNome,
                           searchDataNascimento,
                           searchCartaoSUS,
                           searchMotivoOcorrencia,
                           searchDataOcorrencia,
                           sinanNoticacaoIndividual.id,
                           sinanNoticacaoIndividual.nome_paciente,
                           sinanNoticacaoIndividual.data_nascimento,
                           sinanNoticacaoIndividual.num_cartaosus,
                           sinanViolencia.motivo_ocorrencia,
                           sinanDadosGerais.data_violencia,
                       })
                      .ToList();

            if (!String.IsNullOrEmpty(searchNome))
            {
                obj = obj.Where(a => a.nome_paciente != null && a.nome_paciente.ToUpper().Contains(searchNome.ToUpper()))
                    .ToList();
            }

            if (searchDataNascimento != null)
            {
                obj = obj.Where(a => a.data_nascimento != null && a.data_nascimento.Equals(searchDataNascimento))
                    .ToList();
            }

            if (!String.IsNullOrEmpty(searchCartaoSUS))
            {
                obj = obj.Where(a => a.num_cartaosus != null && a.num_cartaosus.Contains(searchCartaoSUS))
                    .ToList();
            }

            if (searchMotivoOcorrencia > 0)
            {
                obj = obj.Where(a => a.motivo_ocorrencia != null && a.motivo_ocorrencia.Equals(searchMotivoOcorrencia))
                    .ToList();
            }

            if (searchDataOcorrencia != null)
            {
                obj = obj.Where(a => a.data_violencia != null && a.data_violencia.Equals(searchDataOcorrencia))
                    .ToList();
            }            

            var viewmodel = Mapper.Map<List<ListarViewModel>>(obj);

            int paginaTamanho = 5;
            int paginaNumero = (page ?? 1);

            return View(viewmodel.ToPagedList(paginaNumero, paginaTamanho));
        }

        // GET: Sinan/Criar
        public ActionResult Criar()
        {
            return View();
        }

        // POST: Sinan/Criar
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Criar(string submitButton, SinanViewModel viewmodel)
        {
            if (ModelState.IsValid)
            {
                var sinan = new Sinan
                {
                    usu_codigo = Convert.ToInt32(Session["usu_codigo"]),
                    data_envio = DateTime.Now
                };

                _uow.GetRepository<Sinan>().Insert(sinan);
                _uow.GetRepository<Sinan>().Commit();

                var sinanDadosGerais = Mapper.Map<Sinan_DadosGeraisViewModel, Sinan_DadosGerais>(viewmodel.Sinan_DadosGeraisViewModel);
                sinanDadosGerais.id = sinan.id;
                _uow.GetRepository<Sinan_DadosGerais>().Insert(sinanDadosGerais);

                var sinanNotificacaoIndividual = Mapper.Map<Sinan_NotificacaoIndividualViewModel, Sinan_NotificacaoIndividual>(viewmodel.Sinan_NotificacaoIndividualViewModel);
                sinanNotificacaoIndividual.id = sinan.id;
                _uow.GetRepository<Sinan_NotificacaoIndividual>().Insert(sinanNotificacaoIndividual);

                var sinanDadosResidencia = Mapper.Map<Sinan_DadosResidenciaViewModel, Sinan_DadosResidencia>(viewmodel.Sinan_DadosResidenciaViewModel);
                sinanDadosResidencia.id = sinan.id;
                _uow.GetRepository<Sinan_DadosResidencia>().Insert(sinanDadosResidencia);

                var sinanDadosDePessoaAtendida = Mapper.Map<Sinan_DadosDePessoaAtendidaViewModel, Sinan_DadosDePessoaAtendida>(viewmodel.Sinan_DadosDePessoaAtendidaViewModel);
                sinanDadosDePessoaAtendida.id = sinan.id;
                _uow.GetRepository<Sinan_DadosDePessoaAtendida>().Insert(sinanDadosDePessoaAtendida);

                var sinanDadosDaOcorrencia = Mapper.Map<Sinan_DadosDaOcorrenciaViewModel, Sinan_DadosDaOcorrencia>(viewmodel.Sinan_DadosDaOcorrenciaViewModel);
                sinanDadosDaOcorrencia.id = sinan.id;
                _uow.GetRepository<Sinan_DadosDaOcorrencia>().Insert(sinanDadosDaOcorrencia);

                var sinanViolencia = Mapper.Map<Sinan_ViolenciaViewModel, Sinan_Violencia>(viewmodel.Sinan_ViolenciaViewModel);
                sinanViolencia.id = sinan.id;
                _uow.GetRepository<Sinan_Violencia>().Insert(sinanViolencia);

                var sinanViolenciaSexual = Mapper.Map<Sinan_ViolenciaSexualViewModel, Sinan_ViolenciaSexual>(viewmodel.Sinan_ViolenciaSexualViewModel);
                sinanViolenciaSexual.id = sinan.id;
                _uow.GetRepository<Sinan_ViolenciaSexual>().Insert(sinanViolenciaSexual);

                var sinanDadosDoProvavelAutorDaViolencia = Mapper.Map<Sinan_DadosDoProvavelAutorViolenciaViewModel, Sinan_DadosDoProvavelAutorDaViolencia>(viewmodel.Sinan_DadosDoProvavelAutorViolenciaViewModel);
                sinanDadosDoProvavelAutorDaViolencia.id = sinan.id;
                _uow.GetRepository<Sinan_DadosDoProvavelAutorDaViolencia>().Insert(sinanDadosDoProvavelAutorDaViolencia);

                var sinanEncaminhamento = Mapper.Map<Sinan_EncaminhamentoViewModel, Sinan_Encaminhamento>(viewmodel.Sinan_EncaminhamentoViewModel);
                sinanEncaminhamento.id = sinan.id;
                _uow.GetRepository<Sinan_Encaminhamento>().Insert(sinanEncaminhamento);

                var sinanDadosFinais = Mapper.Map<Sinan_DadosFinaisViewModel, Sinan_DadosFinais>(viewmodel.Sinan_DadosFinaisViewModel);
                sinanDadosFinais.id = sinan.id;
                _uow.GetRepository<Sinan_DadosFinais>().Insert(sinanDadosFinais);

                var sinanObservacoes = Mapper.Map<Sinan_ObservacoesViewModel, Sinan_Observacoes>(viewmodel.Sinan_ObservacoesViewModel);
                sinanObservacoes.id = sinan.id;
                _uow.GetRepository<Sinan_Observacoes>().Insert(sinanObservacoes);

                var sinanNotificador = Mapper.Map<Sinan_NotificadorViewModel, Sinan_Notificador>(viewmodel.Sinan_NotificadorViewModel);
                sinanNotificador.id = sinan.id;
                _uow.GetRepository<Sinan_Notificador>().Insert(sinanNotificador);

                _uow.Commit();

                TempData["Success"] = "SINAN Cadastrado";

                return RedirectToAction("Dashboard", "Home");
            }
            else
            {
                return View(viewmodel);
            }
        }

        // GET: Sinan/Editar      
        public ActionResult Editar(int Id)
        {
            var sinan = _uow.GetRepository<Sinan>().GetById(Id);
            var sinanDadosGerais = _uow.GetRepository<Sinan_DadosGerais>().GetById(Id);
            var sinanNotificacaoIndividual = _uow.GetRepository<Sinan_NotificacaoIndividual>().GetById(Id);
            var sinanDadosResidencia = _uow.GetRepository<Sinan_DadosResidencia>().GetById(Id);
            var sinanDadosDePessoaAtendida = _uow.GetRepository<Sinan_DadosDePessoaAtendida>().GetById(Id);
            var sinanDadosDaOcorrencia = _uow.GetRepository<Sinan_DadosDaOcorrencia>().GetById(Id);
            var sinanViolencia = _uow.GetRepository<Sinan_Violencia>().GetById(Id);
            var sinanViolenciaSexual = _uow.GetRepository<Sinan_ViolenciaSexual>().GetById(Id);
            var sinanDadosDoProvavelAutorDaViolencia = _uow.GetRepository<Sinan_DadosDoProvavelAutorDaViolencia>().GetById(Id);
            var sinanEncaminhamento = _uow.GetRepository<Sinan_Encaminhamento>().GetById(Id);
            var sinanDadosFinais = _uow.GetRepository<Sinan_DadosFinais>().GetById(Id);
            var sinanObservacoes = _uow.GetRepository<Sinan_Observacoes>().GetById(Id);
            var sinanNotificador = _uow.GetRepository<Sinan_Notificador>().GetById(Id);

            var viewmodel = new SinanViewModel
            {

SINAN.Presentation.Web/Views/Sinan/Criar.cshtml
@{
    ViewBag.Title = "Criar";
    Layout = "~/Views/Shared/_LayoutSinan.cshtml";
}

@using (Html.BeginForm("Criar", "Sinan", FormMethod.Post,
     new { @class = "form-signin" }))
{
    @Html.AntiForgeryToken()
    @RenderPage("~/Views/Sinan/Sinan.cshtml")   
}

SINAN.Presentation.Web/Views/Sinan/Editar.cshtml
@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_LayoutSinan.cshtml";
}

@using (Html.BeginForm("Editar", "Sinan", FormMethod.Post,
     new { @class = "form-signin" }))
{
    @Html.AntiForgeryToken()
    @RenderPage("~/Views/Sinan/Sinan.cshtml")
}

SINAN.Presentation.Web/Views/Sinan/Listar.cshtml
@using PagedList.Mvc;
@using SINAN.Application.Helpers;

@model PagedList.IPagedList<SINAN.Application.ViewModel.ListarViewModel>

@{
    ViewBag.Title = "Listar";
    Layout = "~/Views/Shared/_LayoutSinan.cshtml";
}

<br>
<br>
<br>

<div class="container">
    <div class="row">
        <div class="py-5 text-center">
            <h2>Consultar</h2>
        </div>
        <br>
        @using (Html.BeginForm("Listar", "Sinan", FormMethod.Get,
            new { id = "Listar", @class = "form-signin" }))
        {
            <div class="form-row">
                <div class="form-group col-md-2">
                    <label>Nome do Paciente</label>
                    @Html.TextBoxFor(model => model.FirstOrDefault().searchNome, new { @type = "text", @class = "form-control", @placeholder = "Nome", autofocus = "" })
                </div>
                <div class="form-group col-md-2">
                    <label>Data Nascimento</label>
                    @Html.TextBoxFor(model => model.FirstOrDefault().searchDataNascimento, new { @type = "date", @class = "form-control" })
                </div>
                <div class="form-group col-md-2">
                    <label>Cartão SUS</label>
                    @Html.TextBoxFor(model => model.FirstOrDefault().searchCartaoSUS, new { @type = "text", @class = "form-control", @placeholder = "Cartão SUS" })
                </div>
                <div class="form-group col-md-2">
                    <label>Motivo Ocorrência</label>
                    @Html.EnumDropDownListFor(model => model.FirstOrDefault().searchMotivoOcorrencia, "-- selecione --", new { @class = "form-control" })
                </div>
                <div class="form-group col-md-2">
                    <label>Data Ocorrência</label>
                    @Html.TextBoxFor(model => model.FirstOrDefault().searchDataOcorrencia, null, new { @type = "date", @class = "form-control" })
                </div>               
                <div class="form-group col-md-2" style="text-align:center">
                    <br />
                    <input class="btn btn-lg btn-danger" type="submit" name="submit" value="Procurar" />                    
                </div>
            </div>           
        }
    </div>
    <div class="row">
        <div class="col-md-12 order-md-12 mb-12">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">
                            </th>
                            <th scope="col">
                            </th>
                            <th scope="col">
                                @Html.DisplayNameFor(model => model.First().nome_paciente)
                            </th>
                            <th scope="col">
                                @Html.DisplayNameFor(model => model.First().data_nascimento)
                            </th>
                            <th scope="col">
                                @Html.DisplayNameFor(model => model.First().num_cartaosus)
                            </th>
                            <th scope="col">
                                @Html.DisplayNameFor(model => model.First().motivo_ocorrencia)
                            </th>
                            <th scope="col">
                                @Html.DisplayNameFor(model => model.First().data_violencia)
                            </th>                           
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <th scope="row">
                                    <a href="@Url.Action("Editar", "Sinan", new { id = item.id })" data-toggle="tooltip" title="Editar">
                                        <span class="glyphicon glyphicon-edit"></span> <small>Editar</small>
                                    </a>
                                </th>
                                <th>
                                    <a href="@Url.Action("Sinan", "Relatorios", new { id = item.id })" target="_blank" data-toggle="tooltip" title="Imprimir">
                                        <span class="glyphicon glyphicon-print"></span> <small>Imprimir</small>
                                    </a>
                                </th>
                                <td>
                                    @Html.DisplayFor(model => item.nome_paciente)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => item.data_nascimento)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => item.num_cartaosus)
                                </td>
                                <td>
                                    @{ string motivo_ocorrencia = item.motivo_ocorrencia == 0 ? "" : item.motivo_ocorrencia.ToDescription(); }
                                    @Html.DisplayFor(model => motivo_ocorrencia)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => item.data_violencia)
                                </td>                               
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 order-md-1 mb-1">
        </div>
        <div id='Paging' class="col-md-4 order-md-1 mb-1" style="text-align:center">
            Página @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
            de @Model.PageCount

            @Html.PagedListPager(Model, page => Url.Action("Listar", "Sinan", new
            {
                page,
                searchNome = Request.QueryString["searchNome"],
                searchDataNascimento = Request.QueryString["searchDataNascimento"],
                searchCartaoSUS = Request.QueryString["searchCartaoSUS"],
                searchMotivoOcorrencia = Request.QueryString["searchMotivoOcorrencia"],
                searchDataOcorrencia = Request.QueryString["searchDataOcorrencia"]
            }))
        </div>
        <div class="col-md-4 order-md-1 mb-1">
        </div>
    </div>
    <br>
</div>