SINAN.Presentation.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using AutoMapper;
using SINAN.Domain.Entities;
using SINAN.Application.Interfaces;
using SINAN.Application.ViewModel;
using SINAN.Infrastructure.CrossCutting.Helpers;

namespace SINAN.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly IUsuarioAppService _usuarioApp;

        public HomeController(IUsuarioAppService usuarioApp)
        {
            _usuarioApp = usuarioApp;
        }

        // GET: Home/Dashboard
        public ActionResult Dashboard()
        {
            return View();
        }

        [Authorize(Roles = "Administrador")]
        public ActionResult CriarConta()
        {
            var viewmodel = new CriarContaViewModel();

            return View(viewmodel);
        }

        // POST: Home/CriarConta
        [Authorize(Roles = "Administrador")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CriarConta(CriarContaViewModel viewmodel)
        {
            if (ModelState.IsValid)
            {
                var usuario = Mapper.Map<CriarContaViewModel, Usuario>(viewmodel);

                usuario.usu_senha = MD5Hash.GetMd5Hash(usuario.usu_senha);
                usuario.usu_datacadastro = DateTime.Now;
                usuario.usu_ativo = true;

                if (ValidarCPF.ValidateCPF(usuario.usu_cpf))
                {
                    var obj = _usuarioApp.Get()
                        .Where(a => a.usu_cpf.Equals(usuario.usu_cpf))
                        .FirstOrDefault();

                    if (obj == null)
                    {
                        var obj_ = _usuarioApp.Get()
                            .Where(a => a.usu_email.Equals(usuario.usu_email))
                            .FirstOrDefault();

                        if (obj_ == null)
                        {
                            _usuarioApp.Insert(usuario);
                            _usuarioApp.Commit();                          

                            TempData["Success"] = "Conta Cadastrada";

                            return RedirectToAction("Dashboard", "Home");
                        }
                        else
                        {
                            TempData["Error"] = "E-mail ja cadastrado";

                            return View(viewmodel);
                        }
                    }
                    else
                    {
                        TempData["Error"] = "CPF ja cadastrado";

                        return View(viewmodel);
                    }
                }
                else
                {
                    TempData["Error"] = "CPF invalido";

                    return View(viewmodel);
                }
            }
            else
            {
                return View(viewmodel);
            }
        }

        // GET: Home/AlteraSenha
        public ActionResult AlterarSenha()
        {
            var viewmodel = new AlterarSenhaViewModel();

            return View(viewmodel);
        }

        // POST: Home/AlteraSenha
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AlterarSenha(AlterarSenhaViewModel viewmodel)
        {
            if (ModelState.IsValid)
            {
                var usuario = Mapper.Map<AlterarSenhaViewModel, Usuario>(viewmodel);

                usuario.usu_codigo = Convert.ToInt32(Session["usu_codigo"]);
                usuario.usu_senha = MD5Hash.GetMd5Hash(viewmodel.usu_senha_anterior);

                var obj = _usuarioApp.Get()
                    .Where(a => a.usu_codigo.Equals(usuario.usu_codigo))
                    .Where(a => a.usu_senha.Equals(usuario.usu_senha))
                    .FirstOrDefault();

                if (obj != null)
                {
                    obj.usu_senha = MD5Hash.GetMd5Hash(viewmodel.usu_senha);

                    _usuarioApp.Update(obj);
                    _usuarioApp.Commit();                    

                    FormsAuthentication.SignOut();
                    Session.Clear();

                    TempData["Success"] = "Senha Alterada";

                    return RedirectToAction("Login", "Account");
                }
                else
                {
                    TempData["Error"] = "A Senha atual esta incorreta";

                    return View(viewmodel);
                }
            }
            else
            {
                return View(viewmodel);
            }
        }

        // GET: Home/Logout
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();

            return RedirectToAction("Login", "Account");
        }
    }
}

SINAN.Presentation.Web/Controllers/SinanController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using PagedList.Mvc;
using AutoMapper;
using PagedList;
using SINAN.Domain.Entities;
using SINAN.Domain.Interfaces.Repository;
using SINAN.Application.Interfaces;
using SINAN.Application.ViewModel;
using SINAN.Infrastructure.CrossCutting.Helpers;

namespace SINAN.Controllers
{
    [Authorize]
    public class SinanController : Controller
    {
        private readonly IUnitOfWork _uow;        
        private readonly IBairroAppService _bairroApp;
        private readonly ILogradouroAppService _logradouroApp;
        private readonly IMunicipioAppService _municipioApp;
        private readonly IUnidadeAppService _unidadeApp;

        public SinanController(IUnitOfWork uow,            
            IBairroAppService bairroApp,
            ILogradouroAppService logradouroApp,
            IMunicipioAppService municipioApp,
            IUnidadeAppService unidadeApp)
        {
            _uow = uow;            
            _bairroApp = bairroApp;
            _logradouroApp = logradouroApp;
            _municipioApp = municipioApp;
            _unidadeApp = unidadeApp;
        }
        
        // GET: Sinan/Listar
        public ActionResult Listar(string searchNome,
            DateTime? searchDataNascimento,
            string searchCartaoSUS,
            int? searchMotivoOcorrencia,
            DateTime? searchDataOcorrencia,
            int? page)
        {
            var obj = (from sinan in _uow.GetRepository<Sinan>().Get()
                       join sinanNoticacaoIndividual in _uow.GetRepository<Sinan_NotificacaoIndividual>().Get() on sinan.id equals sinanNoticacaoIndividual.id
                       join sinanDadosGerais in _uow.GetRepository<Sinan_DadosGerais>().Get() on sinan.id equals sinanDadosGerais.id
                       join sinanViolencia in _uow.GetRepository<Sinan_Violencia>().Get() on sinan.id equals sinanViolencia.id
                       select new
                       {
                           searchNome,
                           searchDataNascimento,
                           searchCartaoSUS,
                           searchMotivoOcorrencia,
                           searchDataOcorrencia,
                           sinanNoticacaoIndividual.id,
                           sinanNoticacaoIndividual.nome_paciente,
                           sinanNoticacaoIndividual.data_nascimento,
                           sinanNoticacaoIndividual.num_cartaosus,
                           sinanViolencia.motivo_ocorrencia,
                           sinanDadosGerais.data_violencia,
                       })
                      .ToList();

            if (!String.IsNullOrEmpty(searchNome))
            {
                obj = obj.Where(a => a.nome_paciente != null && a.nome_paciente.ToUpper().Contains(searchNome.ToUpper()))
                    .ToList();
            }

            if (searchDataNascimento != null)
            {
                obj = obj.Where(a => a.data_nascimento != null && a.data_nascimento.Equals(searchDataNascimento))
                    .ToList();
            }

            if (!String.IsNullOrEmpty(searchCartaoSUS))
            {
                obj = obj.Where(a => a.num_cartaosus != null && a.num_cartaosus.Contains(searchCartaoSUS))
                    .ToList();
            }

            if (searchMotivoOcorrencia > 0)
            {
                obj = obj.Where(a => a.motivo_ocorrencia != null && a.motivo_ocorrencia.Equals(searchMotivoOcorrencia))
                    .ToList();
            }

            if (searchDataOcorrencia != null)
            {
                obj = obj.Where(a => a.data_violencia != null && a.data_violencia.Equals(searchDataOcorrencia))
                    .ToList();
            }            

            var viewmodel = Mapper.Map<List<ListarViewModel>>(obj);

            int paginaTamanho = 5;
            int paginaNumero = (page ?? 1);

            return View(viewmodel.ToPagedList(paginaNumero, paginaTamanho));
        }

        // GET: Sinan/Criar
        public ActionResult Criar()
        {
            return View();
        }

        // POST: Sinan/Criar
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Criar(string submitButton, SinanViewModel viewmodel)
        {
            if (ModelState.IsValid)
            {
                var sinan = new Sinan
                {
                    usu_codigo = Convert.ToInt32(Session["usu_codigo"]),
                    data_envio = DateTime.Now
                };

                _uow.GetRepository<Sinan>().Insert(sinan);
                _uow.GetRepository<Sinan>().Commit();

                var sinanDadosGerais = Mapper.Map<Sinan_DadosGeraisViewModel, Sinan_DadosGerais>(viewmodel.Sinan_DadosGeraisViewModel);
                sinanDadosGerais.id = sinan.id;
                _uow.GetRepository<Sinan_DadosGerais>().Insert(sinanDadosGerais);

                var sinanNotificacaoIndividual = Mapper.Map<Sinan_NotificacaoIndividualViewModel, Sinan_NotificacaoIndividual>(viewmodel.Sinan_NotificacaoIndividualViewModel);
                sinanNotificacaoIndividual.id = sinan.id;
                _uow.GetRepository<Sinan_NotificacaoIndividual>().Insert(sinanNotificacaoIndividual);

                var sinanDadosResidencia = Mapper.Map<Sinan_DadosResidenciaViewModel, Sinan_DadosResidencia>(viewmodel.Sinan_DadosResidenciaViewModel);
                sinanDadosResidencia.id = sinan.id;
                _uow.GetRepository<Sinan_DadosResidencia>().Insert(sinanDadosResidencia);

                var sinanDadosDePessoaAtendida = Mapper.Map<Sinan_DadosDePessoaAtendidaViewModel, Sinan_DadosDePessoaAtendida>(viewmodel.Sinan_DadosDePessoaAtendidaViewModel);
                sinanDadosDePessoaAtendida.id = sinan.id;
                _uow.GetRepository<Sinan_DadosDePessoaAtendida>().Insert(sinanDadosDePessoaAtendida);

                var sinanDadosDaOcorrencia = Mapper.Map<Sinan_DadosDaOcorrenciaViewModel, Sinan_DadosDaOcorrencia>(viewmodel.Sinan_DadosDaOcorrenciaViewModel);
                sinanDadosDaOcorrencia.id = sinan.id;
                _uow.GetRepository<Sinan_DadosDaOcorrencia>().Insert(sinanDadosDaOcorrencia);

                var sinanViolencia = Mapper.Map<Sinan_ViolenciaViewModel, Sinan_Violencia>(viewmodel.Sinan_ViolenciaViewModel);
                sinanViolencia.id = sinan.id;
                _uow.GetRepository<Sinan_Violencia>().Insert(sinanViolencia);

                var sinanViolenciaSexual = Mapper.Map<Sinan_ViolenciaSexualViewModel, Sinan_ViolenciaSexual>(viewmodel.Sinan_ViolenciaSexualViewModel);
                sinanViolenciaSexual.id = sinan.id;
                _uow.GetRepository<Sinan_ViolenciaSexual>().Insert(sinanViolenciaSexual);

                var sinanDadosDoProvavelAutorDaViolencia = Mapper.Map<Sinan_DadosDoProvavelAutorViolenciaViewModel, Sinan_DadosDoProvavelAutorDaViolencia>(viewmodel.Sinan_DadosDoProvavelAutorViolenciaViewModel);
                sinanDadosDoProvavelAutorDaViolencia.id = sinan.id;
                _uow.GetRepository<Sinan_DadosDoProvavelAutorDaViolencia>().Insert(sinanDadosDoProvavelAutorDaViolencia);

                var sinanEncaminhamento = Mapper.Map<Sinan_EncaminhamentoViewModel, Sinan_Encaminhamento>(viewmodel.Sinan_EncaminhamentoViewModel);
                sinanEncaminhamento.id = sinan.id;
                _uow.GetRepository<Sinan_Encaminhamento>().Insert(sinanEncaminhamento);

                var sinanDadosFinais = Mapper.Map<Sinan_DadosFinaisViewModel, Sinan_DadosFinais>(viewmodel.Sinan_DadosFinaisViewModel);
                sinanDadosFinais.id = sinan.id;
                _uow.GetRepository<Sinan_DadosFinais>().Insert(sinanDadosFinais);

                var sinanObservacoes = Mapper.Map<Sinan_ObservacoesViewModel, Sinan_Observacoes>(viewmodel.Sinan_ObservacoesViewModel);
                sinanObservacoes.id = sinan.id;
                _uow.GetRepository<Sinan_Observacoes>().Insert(sinanObservacoes);

                var sinanNotificador = Mapper.Map<Sinan_NotificadorViewModel, Sinan_Notificador>(viewmodel.Sinan_NotificadorViewModel);
                sinanNotificador.id = sinan.id;
                _uow.GetRepository<Sinan_Notificador>().Insert(sinanNotificador);

                _uow.Commit();

                TempData["Success"] = "SINAN Cadastrado";

                return RedirectToAction("Dashboard", "Home");
            }
            else
            {
                return View(viewmodel);
            }
        }

        // GET: Sinan/Editar      
        public ActionResult Editar(int Id)
        {
            var sinan = _uow.GetRepository<Sinan>().GetById(Id);
            var sinanDadosGerais = _uow.GetRepository<Sinan_DadosGerais>().GetById(Id);
            var sinanNotificacaoIndividual = _uow.GetRepository<Sinan_NotificacaoIndividual>().GetById(Id);
            var sinanDadosResidencia = _uow.GetRepository<Sinan_DadosResidencia>().GetById(Id);
            var sinanDadosDePessoaAtendida = _uow.GetRepository<Sinan_DadosDePessoaAtendida>().GetById(Id);
            var sinanDadosDaOcorrencia = _uow.GetRepository<Sinan_DadosDaOcorrencia>().GetById(Id);
            var sinanViolencia = _uow.GetRepository<Sinan_Violencia>().GetById(Id);
            var sinanViolenciaSexual = _uow.GetRepository<Sinan_ViolenciaSexual>().GetById(Id);
            var sinanDadosDoProvavelAutorDaViolencia = _uow.GetRepository<Sinan_DadosDoProvavelAutorDaViolencia>().GetById(Id);
            var sinanEncaminhamento = _uow.GetRepository<Sinan_Encaminhamento>().GetById(Id);
            var sinanDadosFinais = _uow.GetRepository<Sinan_DadosFinais>().GetById(Id);
            var sinanObservacoes = _uow.GetRepository<Sinan_Observacoes>().GetById(Id);
            var sinanNotificador = _uow.GetRepository<Sinan_Notificador>().GetById(Id);

            var viewmodel = new SinanViewModel
            {

SINAN.Presentation.Web/Views/Home/AlterarSenha.cshtml
@model SINAN.Application.ViewModel.AlterarSenhaViewModel
@{
    ViewBag.Title = "Alterar Senha";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}

<br>
<br>
<br>

@using (Html.BeginForm("AlterarSenha", "Home", FormMethod.Post,
     new { id = "alterarsenha", @class = "form-signin" }))
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="row">
            <div class="col-md-4 order-md-1 mb-1">
            </div>
            <div class="col-md-4 order-md-1">
                <div class="py-5 text-center">
                    <h2>Alterar Senha</h2>
                </div>
                <br>
                <div class="mb-3">
                    <label for="senha">Senha Atual</label>
                    @Html.PasswordFor(model => model.usu_senha_anterior, new { @class = "form-control", @placeholder = "*****", autofocus = "" })
                    @Html.ValidationMessageFor(model => model.usu_senha_anterior, "", new { @class = "text-danger" })
                    <br />
                </div>
                <div class="mb-3">
                    <label for="senha">Nova Senha</label>
                    @Html.PasswordFor(model => model.usu_senha, new { @class = "form-control", @placeholder = "*****", })
                    @Html.ValidationMessageFor(model => model.usu_senha, "", new { @class = "text-danger" })
                    <br />
                </div>
                <div class="mb-3">
                    <label for="senha">Confirmar Nova Senha</label>
                    @Html.PasswordFor(model => model.usu_senha_confirma, new { @class = "form-control", @placeholder = "*****", })
                    @Html.ValidationMessageFor(model => model.usu_senha_confirma, "", new { @class = "text-danger" })
                    <br />
                </div>
            </div>
            <div class="col-md-4 order-md-1 mb-1">
            </div>
        </div>
        <div class="row">
            <div class="col-md-5">
            </div>
            <div class="col-md-2">
                <br />
                <input class="btn btn-danger btn-lg btn-block" type="submit" value="Salvar">
                <br />
            </div>
            <div class="col-md-5">
            </div>
        </div>
    </div>
}

<br>
<br>
<br>

SINAN.Presentation.Web/Views/Home/CriarConta.cshtml
@model SINAN.Application.ViewModel.CriarContaViewModel
@{
    ViewBag.Title = "Criar Conta";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}

<br>
<br>
<br>

@using (Html.BeginForm("CriarConta", "Home", FormMethod.Post,
     new { id = "criarconta", @class = "form-signin" }))
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="row">
            <div class="col-md-2 order-md-2 mb-4">
            </div>
            <div class="col-md-8 order-md-1">
                <div class="row">
                    <div class="py-5 text-center">
                        <h2>Criar Conta</h2>
                    </div>
                    <br>
                    <div class="col-md-6 mb-3">
                        <label for="nome">Nome</label>
                        @Html.TextBoxFor(model => model.usu_nome, new { @class = "form-control", @placeholder = "Seu nome completo", autofocus = "" })
                        @Html.ValidationMessageFor(model => model.usu_nome, "", new { @class = "text-danger" })
                        <br />
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="cpf">CPF</label>
                        @Html.TextBoxFor(model => model.usu_cpf, new { @class = "form-control", @placeholder = "123.456.789-00" })
                        @Html.ValidationMessageFor(model => model.usu_cpf, "", new { @class = "text-danger" })
                        <br />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="email">Email</label>
                        @Html.TextBoxFor(model => model.usu_email, new { @class = "form-control", @placeholder = "email@exemplo.com" })
                        @Html.ValidationMessageFor(model => model.usu_email, "", new { @class = "text-danger" })
                        <br />
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="telefone">Telefone</label>
                        @Html.TextBoxFor(model => model.usu_telefone, new { @class = "form-control", @placeholder = "(21) 12345-7890" })
                        @Html.ValidationMessageFor(model => model.usu_telefone, "", new { @class = "text-danger" })
                        <br />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 mb-6">
                        <label for="senha">Perfil</label>
                        @Html.EnumDropDownListFor(model => model.usu_perfil, "-- selecione --", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.usu_perfil, "", new { @class = "text-danger" })
                        <br />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="senha">Senha</label>
                        @Html.PasswordFor(model => model.usu_senha, new { @class = "form-control", @placeholder = "*****" })
                        @Html.ValidationMessageFor(model => model.usu_senha, "", new { @class = "text-danger" })
                        <br />
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="confirmarSenha">Confirmar Senha</label>
                        @Html.PasswordFor(model => model.usu_senha_confirma, new { @class = "form-control", @placeholder = "*****" })
                        @Html.ValidationMessageFor(model => model.usu_senha_confirma, "", new { @class = "text-danger" })
                        <br />
                    </div>
                </div>
            </div>
            <div class="col-md-2 order-md-2 mb-4">
            </div>
        </div>
        <div class="row">
            <div class="col-md-5">
            </div>
            <div class="col-md-2">
                <br />
                <input class="btn btn-lg btn-danger btn-block" type="submit" value="Salvar">
                <br />
            </div>
            <div class="col-md-5">
            </div>
        </div>
    </div>
}

<br>
<br>
<br>

SINAN.Presentation.Web/Views/Home/Dashboard.cshtml
@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}

<br>
<br>

<div id="dash">
    <input class="btn btn-primary btn-lg btn-dash" type="button" value="Consultar" onclick="location.href='@Url.Action("Listar", "Sinan")'" />
    <input class="btn btn-primary btn-lg btn-dash" type="button" value="Nova Ficha" onclick="location.href='@Url.Action("Criar", "Sinan")'" />
</div>